### ISSUE TITLE
Create V.2 Sidebar

### ISSUE THREAD

**Issue by dibleauzah** [phlask/phlask-map#230]
Is your feature request related to a problem? Please describe.
XX

Describe the solution you'd like
XX

Describe alternatives you've considered
XX

Additional context
XX

**Comment by dibleauzah** [comment]
@rh9891 @tnguyen21 @gcardonag: Could you plz remind us what this component does? We're trying to update the ticket. Thanks.

**Comment by nwyin** [comment]
> @rh9891 @tnguyen21 @gcardonag: Could you plz remind us what this component does? We're trying to update the ticket. Thanks.

Poked around the code really briefly and `Sidebar` seems to be an unused component. It's not used anymore and doesn't have any content in the body of the file.

I don't see any use for a `Sidebar` in the application and mock-ups since we only have designs for mobile. Eventually, if we want to build out a desktop version of the Phlask app that's more robust than what we currently have, then we might want a `Sidebar` component. I'm okay with parking this issue and "backlogging" it until we would want to develop a desktop version.

cc: @affabillyty

**Comment by affabillyty** [comment]
Not a current functioning component; closed for now
