### ISSUE TITLE
Update V.2 Crowdsourcing Forms

### ISSUE THREAD

**Issue by CmonUlot** [phlask/phlask-map#314]
**Is your feature request related to a problem? Please describe.**
Before the official launch for PHLASK 2.0, we would like to deploy the updated crowdsourcing forms that can be seen here: https://www.figma.com/file/l0lBzwPalGUg6JjcOXD2Xs/PHLASK--team-library?node-id=518%3A39607&t=lXQ0ULMfCqlCCvxo-1

**Describe the solution you'd like**
A user accessing PHLASK in a Desktop view experiences a design matching the one proposed for PHLASK 2.0. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by CmonUlot** [comment]
@gcardonag anything I should add?

**Comment by tomporvaz** [comment]
Designs here are more up to date: https://www.figma.com/file/VGGqwl3Eq3GQIAO9I6LoNW/PHLASK?type=design&node-id=8036-118940&mode=design&t=UW8Fsxqox4sEh7L6-0

**Comment by Erw1nn** [comment]
Thanks for the heads up

**Comment by Erw1nn** [comment]
Update:

Completed the Mobile version of the Crowdsourcing forms. Currently working on the Desktop version

**Comment by tomporvaz** [comment]
Same as above. Add water done, but refactoring to functional to make next modals easier.

**Comment by lxh5395** [comment]
Using beta site

**Desktop Comments:**
- It seems like the tiles and text are different sizes/spacings when comparing between the resources card and the add site card

- Foraging icon shows briefly but then disappears 

- Titles on the 4 cards (Add XX resource) should be using bolded text (h1 in design library not sure what token that is on your end) and centered within card

- Title bar is missing the closing 'X'

- Title bar is missing curve radius on the upper left and upper right where the color is.

- Seems some of the dropdown inputs are grabbing the wrong styling info, but not all
    - For example, water dispenser type is different then water entry type (styling for entry type is correct)
    
- Missing the page bullet points between chevrons towards the bottom of the card

- Interaction between desktop and mobile are currently different. I think we should follow the mobile interaction of if the add site card is closed and reopened start back at the resource selection instead of where they left off.

**Mobile Comments**
- Padding/margins on add card seems broken, I believe the add page should take up full screen and include spacing between the resource tiles

- Titles on the 4 cards (Add XX resource) should be using bolded text (this time h2 in design library not sure what token that is on your end) and centered within card

- Missing closing 'X' in title bar

- Some dropdowns seem to be grabbing onto the wrong stylings. 
    - For example water dispenser, food type, and food distribution are wrong but organization type is correct. It looks like it might be stemming from dropdowns that are multi select.

- Some of the spacings between fields looks to vary between resource types
    - IE the space between website and description fields on water looks different than the spacing between website and description on foraging
    
- The error message for the name of a foraging site being required is the only bold one, the rest are regular weight, foraging should be fixed to mirror.

- Seems like the box containing the image info (filed types/icon/button) is shifted a little bit towards the left and is not centered in the card

**Comment by Erw1nn** [comment]
I'll look into incorporating this feedback into the forms

**Comment by tomporvaz** [comment]
@Erw1nn Thanks for picking this back up.  I will reopen this ticket, but please let me know if you think any of these review items should be peeled off into a new ticket.

**Comment by tomporvaz** [comment]
The water crowdsourcing form dispenser type should be updated to include a "vessel" as one type in place of both "water jug" and "pitcher" type.  These two types have been consolidated into one type called "vessel" with a recent design update.

![Image](https://github.com/phlask/phlask-map/assets/45155555/f7560dd7-26fc-4fa1-973c-cb3c4d0b5e39)

**Comment by tomporvaz** [comment]
@Erw1nn How is this ticket going?

**Comment by Erw1nn** [comment]
@tomporvaz Hi Tom! I fixed a couple of things but then I had to take a little bit of a break since life got busy for me for a bit. I should be back around next week

**Comment by tomporvaz** [comment]
@Erw1nn I hope everything is going well!  Please let us know if you have made any additional progress, and if you have any updates that we could push to the code base.  We have a goal to get version 2.0 launched by the end of May, and this is by no means the only outstanding ticket, but we would like to wrap up version 2.0 tickets as soon as possible.  You have done fantastic work on this ticket and we appreciate everything you have done to get the crowdsourcing form working.  It's fine if you want to move on from this ticket. I can break out the last couple steps for someone else to work on. Thank you, Tom P

**Comment by Erw1nn** [comment]
Hi @tomporvaz! For the past couple months I've been studying for a couple certs that my job is requiring me to take and it's been taking up a lot of my free time. We may need to reassign this ticket if we're trying to get this to launch soon. I can be available to answer any questions about this task for whoever would like to work on this

**Comment by tomporvaz** [comment]
No problem @Erw1nn !  I will close this ticket as complete, and move the design review requests to a new ticket.  Thanks for all the work you did on this and feel free to jump in any time.
