### ISSUE TITLE
An X that closes the "Resources" modal

### ISSUE THREAD

**Issue by freelyPheobe** [phlask/phlask-map#378]
**Is your feature request related to a problem? Please describe.**
The filter menu should have an X in the top right to close the modal.
![image](https://github.com/phlask/phlask-map/assets/104399179/3f92e9b3-d0e9-4e30-9fb7-1a64dd30b00e)
The X should be in the same spot as the image below.
![image](https://github.com/phlask/phlask-map/assets/104399179/f002f3f7-9b8e-4139-860d-d5a4c1dbd1a0)
https://www.figma.com/file/VGGqwl3Eq3GQIAO9I6LoNW/PHLASK?type=design&node-id=8303-153127&mode=design&t=h61Sy2LRyEsVEiMl-0

**Describe the solution you'd like**
An X that closes the Resources modal

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by JosephAni** [comment]
A close icon button in the filter when the resources button is clicked. Pls review!

![Image](https://github.com/phlask/phlask-map/assets/63737588/5df14678-52eb-497b-9e55-f164af272360)

**Comment by tomporvaz** [comment]
@JosephAni This issue is intended to add closing behavior to the resource menu, and there does not appear to be an X in the figma design for the resource menu.  After discussing this with the designers, we would like the resource menu to close when a user clicks outside of the modal.  So, if a user clicks anywhere on the map, then the resource modal should close. 
![image](https://github.com/phlask/phlask-map/assets/45155555/023e880f-263b-4490-8ed5-5576cd36ac77)

**Comment by JosephAni** [comment]
A custom hook that handles clicks outside the resources modal.

**Comment by tomporvaz** [comment]
I am reopening this until PR #427 is merged.
