### ISSUE TITLE
Dynamic Width for Selected Tap Modal on Desktop

### ISSUE THREAD

**Issue by tomporvaz** [phlask/phlask-map#530]
**Describe the bug**
The selected tap modal expands beyond the bounds of the screen at lower screen widths.  We'd like to make the Selected map modal dynamic so the max width is 708px but it should shrink to a smaller size when the modal expands beyond the bounds of the screen.

![image](https://github.com/user-attachments/assets/8b8f4d5e-d522-4557-a374-de714fec935e)

**To Reproduce**
Use dev tools in responsive mode and set screen width to anywhere between 600px and 768px and notice how the details modal doesn't fit on the screen.  

**Expected behavior**
If the modal doesn't fit on the screen, then the app should display a narrower modal.

**Solution**
Give the modal a dynamic width.

**Comment by GV14982** [comment]
Hm, I'm having trouble reproducing this. When I do dynamic sizing and set it below `900px` it auto switches to the mobile view. Do you have any additional info I might be missing?

**Comment by gcardonag** [comment]
Hi @GV14982 ! I finally did some digging into our PR history and found that we did kind-of fix this about a week later via https://github.com/phlask/phlask-map/pull/533/ but didn't link that PR to this issue. Because of that, I think this should be closed. Thank you for taking the time to confirm the bug can no longer be reproduced! 🙏
