### ISSUE TITLE
Resources Button does not toggle Resources Menu Off

### ISSUE THREAD

**Issue by tomporvaz** [phlask/phlask-map#532]
**Describe the bug**
When the resources modal is open, I click the resources button again to close the modal, but it does not close.  The resouce modal button should behave like the filter button, and toggle the resources button open and close.  

https://github.com/user-attachments/assets/8618ca90-7de3-430c-bbbd-966b69edca7c

**To Reproduce**
Click Resources button to open modal, click it again to close Resources modal.

**Expected behavior**
toggle

**Comment by GV14982** [comment]
This appears to be a race condition between these two dispatches to the redux store:

- [toolbar click](https://github.com/phlask/phlask-map/blob/a62595c3d0d73c9b938dc7ba4a8379a2a1a52abf/src/components/Toolbar/Toolbar.js#L139)
- [click outside modal](https://github.com/phlask/phlask-map/blob/a62595c3d0d73c9b938dc7ba4a8379a2a1a52abf/src/components/ChooseResourceType/DesktopChooseResourceType.js#L56)

I noticed none of the other modals have this "click outside" feature. Easiest solution is to just remove that. Otherwise I can try and find a way to debounce the state updates, but that might take me a little longer. Thoughts? @gcardonag @RNR1

**Comment by gcardonag** [comment]
Good find @GV14982 ! The two dispatches line up with what I found on Redux toolkit. As far as a fix, we talked about it on standup and agreed upon debouncing the dispatch done inside the `handleClickOutside`
